name: test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.1.2
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  retrofit: ^4.6.0
  surf_lint_rules: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0

flutter:
  uses-material-design: true
